### PR TITLE
Mock attribute workaround for project and key

### PR DESCRIPTION
**Pull request by jtsaito**

### CODE REVIEW

**Comment by awendt** [comment]
@jtsaito how would this option be used?

**Comment by jtsaito** [comment]
Closing

**Comment by jtsaito** [comment]
Keeping for until after today's standup.

**Comment by jtsaito** [comment]
@awendt We tried to disable Rollbar API read operations when the Rollbar API was down for half a day and we could not apply Terraform changes. It's probably no longer needed.

**Pull request closed without merging**
